### ISSUE TITLE
Bug with Blood Pressure History chips!!

### ISSUE THREAD

**Issue by lorayzy** [DavidCasc/cardiac_corner_app#21]

**Comment by lorayzy** [comment]
Basically I noticed the wrong chips show up in the list view than what was selected.

**Comment by lorayzy** [comment]
![image](https://user-images.githubusercontent.com/93155835/148455134-ca2fb53e-05cc-4eaf-bf4b-a4e73c8c3796.png)

**Comment by lorayzy** [comment]
![image](https://user-images.githubusercontent.com/93155835/148455207-02e54f21-5059-4f33-89e0-111887c6a3a4.png)

**Comment by lorayzy** [comment]
Same applies when i click Stress and Heavy Exercise (it'll show Sodium and Stress instead)

**Comment by DavidCasc** [comment]
it goes exercise sodium stress
 it had sodium stress exercise
