### ISSUE TITLE
Breakdown screen does not show newly inputted measurement

### ISSUE THREAD

**Issue by lorayzy** [DavidCasc/cardiac_corner_app#22]
Breakdown screen graphs do not show newly inputted measurement.

For example, the image below is the breakdown screen after I put "200/100" as the BP. This 200/100 should be visible on this screen but it is not.

![image](https://user-images.githubusercontent.com/93155835/148832116-36f29c5e-f64d-4ebf-8c59-67e139981de4.png)

**Comment by DavidCasc** [comment]
I'll probably have to change the writing functions 
https://stackoverflow.com/questions/5960678/whats-the-difference-between-commit-and-apply-in-sharedpreferences
Currently using commit() but will most likely have to use apply()

**Comment by DavidCasc** [comment]
Fixed in recent commit
